name: Release

on:
  push:
    tags:
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean --skip=validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: v0.1.0
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          
permissions:
  contents: write
  packages: write
  issues: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'
          check-latest: true

      - name: Clean Go module cache
        run: rm -rf $GOPATH/pkg/mod

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: make deps

      - name: Run tests
        run: make test

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean --skip=validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ github.ref_name }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}

      - name: Update CHANGELOG
        run: |
          # Extract version from tag
          VERSION=${GITHUB_REF#refs/tags/}
          DATE=$(date +%Y-%m-%d)
          
          # Update CHANGELOG.md
          sed -i "s/## \[Unreleased\]/## [Unreleased]\n\n## [$VERSION] - $DATE/" CHANGELOG.md
          
          # Add new comparison link
          sed -i "/\[Unreleased\]:/c\\[Unreleased\\]: https://github.com/$GITHUB_REPOSITORY/compare/$VERSION...HEAD\n[$VERSION]: https://github.com/$GITHUB_REPOSITORY/compare/v$(echo $VERSION | awk -F. '{print $1"."$2"."$3-1}')...$VERSION" CHANGELOG.md
          
          echo "CHANGELOG updated for $VERSION"
